version: 2
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - gosec
    - bodyclose
    - nolintlint
    - errcheck
linters-settings:
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        disabled: true
  gosec:
    config:
      G306: "0600"
  nolintlint:
    allow-unused: true
    allow-no-explanation: []
    require-explanation: true
    require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - nolintlint
