#!/bin/bash
# scripts/generate-juice.sh — Agent.4 Brand "Juice" Generation
# Parses .agent/rules/brand.toon and generates CSS variables and Go constants.

set -e

TOON_FILE=".agent/rules/brand.toon"
CSS_OUT="ui/static/css/brand-tokens.css"
GO_OUT="internal/domain/brand.go"

# Root directory check
if [ ! -f "$TOON_FILE" ]; then
    echo "Error: $TOON_FILE not found. Run from project root."
    exit 1
fi

echo "/* ── Generated Brand Tokens (DO NOT EDIT) ── */" > "$CSS_OUT"
echo ":root {" >> "$CSS_OUT"

# Parse colors
grep -A 100 "colors {" "$TOON_FILE" | grep -m 1 -B 100 "}" | grep ":" | while read -r line; do
    key=$(echo "$line" | cut -d: -f1 | xargs)
    val=$(echo "$line" | cut -d: -f2 | cut -d/ -f1 | xargs)
    # Convert camelCase to kebab-case for CSS
    kebab_key=$(echo "$key" | sed 's/\([a-z0-9]\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')
    echo "  --brand-color-$kebab_key: $val;" >> "$CSS_OUT"
done

# Parse radius
grep -A 100 "radius {" "$TOON_FILE" | grep -m 1 -B 100 "}" | grep ":" | while read -r line; do
    key=$(echo "$line" | cut -d: -f1 | xargs)
    val=$(echo "$line" | cut -d: -f2 | cut -d/ -f1 | xargs)
    echo "  --brand-radius-$key: $val;" >> "$CSS_OUT"
done

# Parse space
grep -A 100 "space {" "$TOON_FILE" | grep -m 1 -B 100 "}" | grep ":" | while read -r line; do
    key=$(echo "$line" | cut -d: -f1 | xargs)
    val=$(echo "$line" | cut -d: -f2 | cut -d/ -f1 | xargs)
    echo "  --brand-space-$key: $val;" >> "$CSS_OUT"
done

# Parse motion
grep -A 100 "motion {" "$TOON_FILE" | grep -m 1 -B 100 "}" | grep ":" | while read -r line; do
    key=$(echo "$line" | cut -d: -f1 | xargs)
    val=$(echo "$line" | cut -d: -f2 | cut -d/ -f1 | xargs)
    kebab_key=$(echo "$key" | sed 's/\([a-z0-9]\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')
    echo "  --brand-motion-$kebab_key: $val;" >> "$CSS_OUT"
done

echo "}" >> "$CSS_OUT"
echo "Generated $CSS_OUT"

# Generate Go Constants
cat <<EOF > "$GO_OUT"
// Code generated by scripts/generate-juice.sh. DO NOT EDIT.
package domain

const (
EOF

# Parse colors for Go (PascalCase)
grep -A 100 "colors {" "$TOON_FILE" | grep -m 1 -B 100 "}" | grep ":" | while read -r line; do
    key=$(echo "$line" | cut -d: -f1 | xargs)
    val=$(echo "$line" | cut -d: -f2 | cut -d/ -f1 | xargs | tr -d ';')
    pascal_key="$(tr '[:lower:]' '[:upper:]' <<< ${key:0:1})${key:1}"
    echo "	BrandColor$pascal_key = \"$val\"" >> "$GO_OUT"
done

echo ")" >> "$GO_OUT"
echo "Generated $GO_OUT"
