// Code generated by scripts/generate-juice.sh. DO NOT EDIT.
package domain

const (
	BrandColorPrimary    = "#FF8A00"
	BrandColorEarthDark  = "#1A120E"
	BrandColorEarthClay  = "#A0522D"
	BrandColorEarthOchre = "#CC7722"
	BrandColorEarthSand  = "#F4EBD0"
	BrandColorEarthCream = "#FAF8F1"
	BrandColorSecondary  = "#005D3A"
	BrandColorAccent     = "#F58608"
)
