version: 2
linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - revive
    - gosec
    - misspell
    - unparam
    - prealloc
    - whitespace
    - bodyclose
    - noctx
    - errorlint
    - copyloopvar

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: HEAD

run:
  timeout: 5m
  tests: true
